### ISSUE TITLE
Enanchement proposal

### ISSUE THREAD

**Issue by Darelbi** [tghosgor/threadpool11#5]
Hi, first of all thanks for this great library, due to few my personal benchmarks is the only one without deadlocks (every other thread pool i tested under pressure just deadlocked soon or later) and is also the fastest, but I think it needs a way to support futures. Without that it loses much of its potential (performance).

"waitAll" is simple and effective but odd, if I have a 5 core processor the most natural way to proceed is to split the job into 4/5 threads, however they never get scheduled at 100% so one thread will always finish first and another one later: this causes a deltaTime, so you get a performance penalty of "deltaTime \* number of jobs to split". statistically you can reduce deltaTime by splitting the jobs amongst greater number of threads (wich is not optimal). So the way to go is to wait only the threads that you need to wait (using futures!). This gives a perfomance penality wich is only "deltaTime*1" and allows also a nice thing : smaller jobs can be assigned to fewer number of threads to reduce the scheduling overhead and this allows to start early bigger jobs (this is not possibile using "waitAll" because if you split a job amogst fewer threads you just keep some CPU cores in idle reducing application throughput).. If you can implement this feature I'll spread the word for you :)

If you can't do that I don't know when I'll have the time to create my pool .. sigh XD 

sincerely Dario

**Comment by tghosgor** [comment]
Hi. It sounds like a good idea but unfortunately I haven't ever used std::future in anywhere so I don't know their behavior / usage style. It is certainly a good research subject for me and luckily I like learning new things so I will look into this but I am a little bit over my head right now so it may take some time.

I have created a new branch named [future](https://github.com/metherealone/threadpool11/tree/future) for progress on this.

**Comment by tghosgor** [comment]
This looks like it will be a really nice feature. My initial readings showed I may also allow to get the the return value of the posted work with a std::promise/future combination, correct me if I am wrong about my first impressions about promise/future please.

**Comment by Darelbi** [comment]
yeah! You are right :) I forgot to mention that this should be used with "promise" else is almost useless. Actually users can put the promise/future inside the lambda and that would work, but having it provided at library level is much simpler :).

Just a note: seems that on GCC "condition_variable" is bugged, so if you find yourself needing to use it, use "condition_variable_any" instead :) (just spent the evening on that issue).

I'm already following you for updates:)

**Comment by tghosgor** [comment]
Library already uses condition_variable but haven't noticed anything yet but will change it then.

I am thinking of converting this into a header only library since there will be heavy template usage (core functions) and library is relatively small anyway.

My idea is promise will be internal and postWork will return a std::future for now.

**Comment by Darelbi** [comment]
Seems good:) I'm indifferent to headers only or no. I just hope you don't end with something similiar:

template < typename ReturnType, typename... Args >
class ThreadPool < ReturnType(Args...) >{

A single pool must handle different types:)

so

class ThreadPool{ //and looks nicer!

**Comment by tghosgor** [comment]
Yeah I was just thinking about that and it may require weird pointer casts. Pool won't be templated but Worker class may be. Then pool will have an array of pointers and some pointer casts there.

I can easily do this if no return value is needed with no templates and all, I personally hate return values anyway and try to pass by reference all the time. I don't know if it is worth the complication it will create. Is there any benefit that return value will give compared to a void WorkHandle::wait() because I might go with the second option, which feels more "free" from users point of view according to me.

**Comment by tghosgor** [comment]
I came up with a considerably clean way (there is one copying construction of work function (in lambda) that I cannot seem to avoid). I have pushed the changes to the future branch.

I will be glad if you can test the new Pool::postWork returning a std::future object. There is a new demo in the demo source file about the future usage. Also please compare the overhead of the added future/promise objects to the old master branch. (1000000 work posting demo takes twice, three times as much time compared to master for me but it is very little if we divide it to 1000000 and the posted function does nothing at all.) Also you could do your other stability tests for deadlocks and check for memory leak.

future branch also includes a fix for a bug (deadlock or system_error exception) for Pool::decreaseWorkerCount that has been in the master branch for a long time and still is for now.

**Comment by tghosgor** [comment]
I have also added a hackish moving of work objects to lambda.

**Comment by tghosgor** [comment]
I am taking a new approach to this. I will do some great code changes and remove some api. I will be renaming the current stable master to 1.0.0 and create a 2.0-dev branch and do a redesign there. waitAll won't be necessary anymore and such, futures can be pushed into a vector and get can be called all of them to imitate waitAll and some mutexes can be removed this way.

**Comment by Darelbi** [comment]
waitAll is still convenient

currently the future branch is crashing here's the test code (expires in 1 month):

http://pastebin.com/m3CJFNi0

i think it's still missing the destructor (rules of five)

**Comment by tghosgor** [comment]
waitAll needs another -now unnecessary- mutex so it should be gone. A batch of works could be sent and via a variadic helper function later if necessary and be waited on. I will notify here when it is stable enough to test. I will also be doing some internal changes such as splitting workers into two `std::list`s instead of one `std::deque` which will allow a better lock/unlock mutex layout (right now posting work and finishing works use the same mutex). (It was already like this before if I remember right, I don't remember why I changed it but I see no reason not to use two lists now)

**Comment by tghosgor** [comment]
Okay, please checkout [2.0-dev branch](https://github.com/metherealone/threadpool11/tree/2.0-dev) and test for deadlocks etc. It passed my personal stress tests and I have noticed that version 1.0 might have been fast because it seems like it could have left some works queued yet threads signalled done to `Pool::waitAll`.

Anyway this new version is way more restrictive about mutual exclusions and seems rock solid to me, passed stress tests like I said.

Looking forward to get feedback.

**Comment by Darelbi** [comment]
it just crash in all 3 tests (TEST_0, TEST_1, TEST_2):
http://pastebin.com/dmW22WrB

also as side note, you should not use "rand()" in your demo because rand is not thread safe (well that don't really matters since you want random numbers so undefined behaviour is fine anyway XD)

Your demo run fine :). Seems that the test code I'm using is making recursively falling a number of thread pools implementations, I reviewed it many times but it is correct XD.

compiler flags:
-g -O2 -std=c++11
compiler version:
GCC 4.8.0 posix ljsj
os:
win vista

STACK TRACE (screenshot, because IDE don't allow copy-paste all at once, it allows just to copy line by line so screenshot was faster):
http://i.imgur.com/qUoiCHZ.jpg

**Comment by tghosgor** [comment]
`recursiveWork(pool,depth--);` line is post-decrement and will cause the recursion go on forever and probably stack overflow or something. I converted it to pre-decrement while testing. However there was also something wrong with the destruction of Pool. I have added necessary Worker desctructors for Pool to safely destruct.

In TEST_0 I have experienced a deadlock that I can't reproduce (may not actually be a deadlock and some memory error locking). However I have experienced a std::list corruption with TEST_2. I will look into that.

Changed are pushed to -dev. I will give updates when I feel like it is stable. Thank you for your time.

**Comment by Darelbi** [comment]
Nice:) sorry for the post decrement, originally it was just a -1 but I have bad habit of "rewrite" to make code nicer. I put a comment, else next time see -1 I change it again to -- O_O. I wait for next changes:)

If you have problem that can't be solved remeber also to use "condition_variable_any" and see if that works.

**Comment by tghosgor** [comment]
Apparently the list problem was me not knowing `std::list::splice`'s iterator behavior in C++11. I have fixed various bugs I have seen and pushed the changed to -dev. All of your tests are passing without a problem now.

I will be glad if you test further. I will be testing some performance options (two `std::list`s vs one `std::vector` and an active flag in `Worker` and such.).

P.S. The test you posted is in the repo now as tests.cpp under demo for me to use in the future.

**Comment by tghosgor** [comment]
I previously stated version 1.0 was too fast that it may not be finishing all the works when `Pool::waitAll()` is called but I was wrong. I managed to get the 2.0-dev branch almost as fast as 1.0.

**Comment by Darelbi** [comment]
Nice  I take immediatly a look :)

**Comment by Darelbi** [comment]
seems to work to me :) and is about 20% faster than the fastest pool I tried:) (100ns/jobs on my machine under TEST1). Also used in my real app without problems.

**Comment by tghosgor** [comment]
Thanks for the feedback. This made me refactor most of the code and it was badly designed at its time apparently. Will remove the -dev tag after I thoroughly review the code.

**Comment by tghosgor** [comment]
I have pushed a big change to 2.0-dev that uses boost::lockfree now. It utilizes the CPU Cores up to 100% now and is extremely fast _for actual work that takes time_, compared the old implementation. It made me remove some functions like `Pool::getActiveWorkers` and such (now there is only `getWorkers`), which were almost useless anyway, for the sake of speed. There isn't much noticeable performance gain in empty functions but if you do something like

```
volatile uint16_t var = 0;
while(++var < (std::numeric_limits<uint16_t>::max()));
```

it is 10~20 times faster than the old code. Feel free to make tests. Some usability functions like decreaseWorkerCount etc. are not yet implemented.

**Comment by Darelbi** [comment]
will you mantain both versions or just the one with boost?

**Comment by tghosgor** [comment]
I am leaning towards only maintaining the one with boost because it is a header only library. No need to even compile boost, I don't know about boost license but I guess I may even put it in repo. Also, the removed functions were useless anyway.

**Comment by Darelbi** [comment]
not everyone like boost as dependency (boost license is fine, it is similiar to MIT license). Boost is very worth but I tend to avoid using it in any public code (many libraries, for example AssImp, use boost but can also be compiled without boost)

**Comment by tghosgor** [comment]
Added to repo. It uses Boost if you have it or the one in the repo if not.

**Comment by tghosgor** [comment]
v2.0.0 has been officially released after I did tests and found it to be stable.

It is also a lot faster on real workloads and fully utilizes all cores.
